name: Accept Package Upload

on:
  repository_dispatch:
    types: [upload-package]

jobs:
  process-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Process package upload
      run: |
        echo "Package upload request received"
        echo "Package URL: ${{ github.event.client_payload.package_url }}"
        echo "Package Name: ${{ github.event.client_payload.package_name }}"
        echo "Distribution: ${{ github.event.client_payload.distribution }}"
        echo "Component: ${{ github.event.client_payload.component }}"
        echo "Sender: ${{ github.event.client_payload.sender }}"
        
        # Create incoming directory
        mkdir -p incoming
        
        # Download the package
        if [ -n "${{ github.event.client_payload.package_url }}" ]; then
          PACKAGE_NAME="${{ github.event.client_payload.package_name }}"
          
          echo "Downloading to: incoming/$PACKAGE_NAME"
          curl -L -o "incoming/$PACKAGE_NAME" "${{ github.event.client_payload.package_url }}"
          echo "Package downloaded successfully"
          
          # Check what we actually downloaded
          echo "File info:"
          ls -la "incoming/$PACKAGE_NAME"
          echo "File type:"
          file "incoming/$PACKAGE_NAME"
          echo "File size: $(stat -f%z "incoming/$PACKAGE_NAME" 2>/dev/null || stat -c%s "incoming/$PACKAGE_NAME")"
          
          # Check if it's actually a .deb file (sometimes downloads fail silently)
          if [ ! -f "incoming/$PACKAGE_NAME" ]; then
            echo "Error: Downloaded file does not exist"
            exit 1
          fi
          
          # Check file size (should be larger than a few KB for a real package)
          FILE_SIZE=$(stat -f%z "incoming/$PACKAGE_NAME" 2>/dev/null || stat -c%s "incoming/$PACKAGE_NAME")
          if [ "$FILE_SIZE" -lt 1000 ]; then
            echo "Error: Downloaded file is too small ($FILE_SIZE bytes), likely an error page"
            echo "File contents:"
            cat "incoming/$PACKAGE_NAME"
            exit 1
          fi
          
          # Verify it's a valid .deb file
          if file "incoming/$PACKAGE_NAME" | grep -q "Debian binary package"; then
            echo "Valid Debian package confirmed"
            
            # Commit the package to trigger rebuild
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add incoming/
            git commit -m "Add package: $PACKAGE_NAME"
            git push
          else
            echo "Error: Invalid package file"
            echo "File type check failed for: incoming/$PACKAGE_NAME"
            rm "incoming/$PACKAGE_NAME"
            exit 1
          fi
        else
          echo "Error: No package URL provided"
          exit 1
        fi
